# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Chris Prezioso
title: My BIG 
email: 
phone: 
website:

# Social links
twitter_username:
github_username:  
dribbble_username: 
facebook_username:
flickr_username: 
instagram_username: laurens__big1
linkedin_username: 
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username:
